###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "root",
  "name": "Superuser",
  "password": "salainen"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "mluukkai",
  "name": "Matti Luukkainen",
  "password": "salainen"
}

### Fails - username already taken
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "mluukkai",
  "name": "Matti Luukkainen",
  "password": "salainen"
}

### Fails - username must be a minimum of 4 characters
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "lim",
  "name": "Lim",
  "password": "salainen"
}

### Fails - username should have only alphabets; no special characters and no numbers allowed
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "lima45",
  "name": "Lima",
  "password": "salainen"
}

### Fails - username should have only alphabets; no special characters and no numbers allowed
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "limaak!!",
  "name": "Lima",
  "password": "salainen"
}

### 
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "polly",
  "name": "Polly",
  "password": "salainen"
}
