PUT http://localhost:3001/api/notes/65284213802beff339a7a631
Content-Type: application/json

{
  "content": "HTML (Hypertext Markup Language) is easy"
}

###
PUT http://localhost:3001/api/notes/65284213802beff339a7a631
Content-Type: application/json

{
  "content": "lol"
}